module.exports = {
    CPF_NOT_VALID: 'CPF_NOT_VALID',
    CPF_REQUIRED: 'CPF_REQUIRED',
    JOB_NAME_REQUIRED: 'JOB_NAME_REQUIRED',
    TEXT_VALUE_REQUIRED: 'TEXT_VALUE_REQUIRED',
    TEXT_KEY_WORDS_REQUIRED: 'TEXT_KEY_WORDS_REQUIRED',
    SAVED_TEXT: 'SAVED_TEXT',
    DUPLICATE_TEXT: 'DUPLICATE_TEXT',
    STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
};